### ISSUE TITLE
[FR] Incident Report Form

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/Simulert#1]
**Tasks**

- [ ] Form Styling
- [ ] Form Access without Login
- [ ] Document Upload Section
- [ ] Other Option Pop-Ups/Fields
- [ ] Submission Confirmation
