### ISSUE TITLE
[FR] User Authentication

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/Simulert#2]
**Tasks**

- [ ] Form Styling for login.html
- [ ] Log-In Function
- [ ] Check Authentication Function
- [ ] Log-Out Function
- [ ] Blocking from backend if not authenticated
- [ ] Role based users
- [ ] Link users to organisations
