### ISSUE TITLE
[FR] Incident Details (Backend)

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/Simulert#4]
**Tasks**

- [ ] Details Styling (Backend)
- [ ] Log Function Visible
- [ ] Status Change Functions
- [ ] Comment Function
- [ ] File Viewer
- [ ] Management Panel for Incident Details
