### ISSUE TITLE
[FR] Incident Details (Frontend)

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/Simulert#5]
**Tasks**

- [ ] Details Styling (Frontend)
- [ ] Log Function Visible
- [ ] Status Change Functions
- [ ] Chat Function
- [ ] File Viewer
- [ ] File Uploading
