### ISSUE TITLE
[FR] Notification System

### ISSUE THREAD

**Issue by smcnab1** [smcnab1/Simulert#6]
**Tasks**

- [ ] Email for Accounts
- [ ] Chat Function Notifications
- [ ] New Report for Reporter
- [ ] New Report for Investigating Manager
